// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vor1k_pu.h for the primary calling header

#ifndef _VOR1K_PU_OR1K_PU_H_
#define _VOR1K_PU_OR1K_PU_H_  // guard

#include "verilated_heavy.h"
#include "Vor1k_pu__Dpi.h"

//==========

class Vor1k_pu__Syms;
class Vor1k_pu_VerilatedVcd;
class Vor1k_pu_or1k_core__pi1;
class Vor1k_pu_mpsoc_wb_spram__D800000;


//----------

VL_MODULE(Vor1k_pu_or1k_pu) {
  public:
    // CELLS
    Vor1k_pu_or1k_core__pi1* core;
    Vor1k_pu_mpsoc_wb_spram__D800000* wb_bfm_memory0;
    
    // PORTS
    VL_IN8(wb_clk_i,0,0);
    VL_IN8(wb_rst_i,0,0);
    VL_IN8(tck_pad_i,0,0);
    VL_OUT8(tdo_pad_o,0,0);
    VL_IN8(tms_pad_i,0,0);
    VL_IN8(tdi_pad_i,0,0);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__biu_rst;
        CData/*0:0*/ __PVT__wb_s2m_or1k_d_ack;
        CData/*0:0*/ __PVT__wb_s2m_or1k_d_err;
        CData/*0:0*/ __PVT__wb_s2m_or1k_i_ack;
        CData/*0:0*/ __PVT__wb_s2m_or1k_i_err;
        CData/*0:0*/ __PVT__wb_m2s_dbg_cyc;
        CData/*0:0*/ __PVT__wb_m2s_dbg_stb;
        CData/*0:0*/ __PVT__wb_s2m_dbg_ack;
        CData/*0:0*/ __PVT__wb_s2m_dbg_err;
        CData/*2:0*/ __PVT__wb_m2s_mem_cti;
        CData/*3:0*/ __PVT__wb_m2s_uart_sel;
        CData/*7:0*/ __PVT__wb_s2m_uart_dat;
        CData/*0:0*/ __PVT__wb_s2m_uart_ack;
        CData/*0:0*/ __PVT__or1k_dbg_stb_i;
        CData/*0:0*/ __PVT__or1k_dbg_stall_i;
        CData/*0:0*/ __PVT__or1k_dbg_ewt_i;
        CData/*3:0*/ __PVT__or1k_dbg_lss_o;
        CData/*1:0*/ __PVT__or1k_dbg_is_o;
        CData/*0:0*/ __PVT__or1k_dbg_rst;
        CData/*0:0*/ __PVT__or1k_rst;
        CData/*0:0*/ __PVT__uart_irq;
        CData/*0:0*/ __PVT__wb_interface0__DOT__wb_mux_or1k_d__DOT__wbm_err;
        CData/*0:0*/ __PVT__wb_interface0__DOT__wb_mux_or1k_d__DOT__slave_sel;
        CData/*1:0*/ __PVT__wb_interface0__DOT__wb_mux_or1k_d__DOT__match;
        CData/*0:0*/ __PVT__wb_interface0__DOT__wb_mux_or1k_i__DOT__wbm_err;
        CData/*0:0*/ __PVT__wb_interface0__DOT__wb_mux_or1k_i__DOT__slave_sel;
        CData/*0:0*/ __PVT__wb_interface0__DOT__wb_mux_dbg__DOT__wbm_err;
        CData/*0:0*/ __PVT__wb_interface0__DOT__wb_mux_dbg__DOT__slave_sel;
        CData/*2:0*/ __PVT__wb_interface0__DOT__wb_arbiter_mem__DOT__grant;
        CData/*1:0*/ __PVT__wb_interface0__DOT__wb_arbiter_mem__DOT__master_sel;
        CData/*0:0*/ __PVT__wb_interface0__DOT__wb_arbiter_mem__DOT__active;
        CData/*0:0*/ __PVT__wb_interface0__DOT__wb_arbiter_mem__DOT__arbiter0__DOT__next;
        CData/*2:0*/ __PVT__wb_interface0__DOT__wb_arbiter_mem__DOT__arbiter0__DOT__order;
        CData/*2:0*/ __PVT__wb_interface0__DOT__wb_arbiter_mem__DOT__arbiter0__DOT__token;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__tdo_padoe_o;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__test_logic_reset;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__run_test_idle;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__select_dr_scan;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__capture_dr;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__shift_dr;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__exit1_dr;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__pause_dr;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__exit2_dr;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__update_dr;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__select_ir_scan;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__capture_ir;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__shift_ir;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__shift_ir_neg;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__exit1_ir;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__pause_ir;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__exit2_ir;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__update_ir;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__extest_select;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__sample_preload_select;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__idcode_select;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__mbist_select;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__debug_select;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__bypass_select;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__tms_q1;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__tms_q2;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__tms_q3;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__tms_q4;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__tms_reset;
        CData/*3:0*/ __PVT__jtag_tap0__DOT__jtag_ir;
    };
    struct {
        CData/*3:0*/ __PVT__jtag_tap0__DOT__latched_jtag_ir;
        CData/*3:0*/ __PVT__jtag_tap0__DOT__latched_jtag_ir_neg;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__instruction_tdo;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__idcode_tdo;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__bypassed_tdo;
        CData/*0:0*/ __PVT__jtag_tap0__DOT__bypass_reg;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb_rst_i;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu1_clk_i;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu1_bp_i;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu1_stall_o;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu1_stb_o;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu1_we_o;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu1_ack_i;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu1_rst_o;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb_jsp_cyc_i;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb_jsp_stb_i;
        CData/*3:0*/ __PVT__dbg_if0__DOT__wb_jsp_sel_i;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb_jsp_we_i;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb_jsp_cab_i;
        CData/*2:0*/ __PVT__dbg_if0__DOT__wb_jsp_cti_i;
        CData/*1:0*/ __PVT__dbg_if0__DOT__wb_jsp_bte_i;
        CData/*1:0*/ __PVT__dbg_if0__DOT__module_id_reg;
        CData/*3:0*/ __PVT__dbg_if0__DOT__module_selects;
        CData/*3:0*/ __PVT__dbg_if0__DOT__module_inhibit;
        CData/*5:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__bit_count;
        CData/*3:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__operation;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__internal_register_select;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__addr_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__addr_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__op_reg_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__bit_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__bit_ct_rst;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__word_ct_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__word_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__out_reg_ld_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__out_reg_shift_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__out_reg_data_sel;
        CData/*1:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__tdo_output_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__biu_strobe;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__crc_clr;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__crc_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__crc_in_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__crc_shift_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__regsel_ld_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__intreg_ld_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__error_reg_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__biu_clr_err;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__bit_count_max;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__biu_ready;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__burst_instruction;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__rd_op;
        CData/*5:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__word_size_bits;
        CData/*2:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__word_size_bytes;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__crc_data_in;
        CData/*3:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__module_state;
        CData/*3:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__module_next_state;
        CData/*3:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__sel_reg;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__wr_reg;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__str_sync;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__rdy_sync;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__err_reg;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__rdy_sync_tff1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__rdy_sync_tff2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__rdy_sync_tff2q;
    };
    struct {
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__str_sync_wbff1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__str_sync_wbff2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__str_sync_wbff2q;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__data_o_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__rdy_sync_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__err_en;
        CData/*3:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__be_dec;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__start_toggle;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__wb_fsm_state;
        CData/*0:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__next_fsm_state;
        CData/*5:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__bit_count;
        CData/*3:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__operation;
        CData/*1:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__internal_reg_status;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__internal_register_select;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__addr_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__addr_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__op_reg_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__bit_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__bit_ct_rst;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__word_ct_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__word_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__out_reg_ld_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__out_reg_shift_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__out_reg_data_sel;
        CData/*1:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__tdo_output_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__biu_strobe;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__crc_clr;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__crc_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__crc_in_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__crc_shift_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__regsel_ld_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__intreg_ld_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__biu_ready;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__burst_instruction;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__crc_data_in;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__status_reg_wr;
        CData/*3:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__module_state;
        CData/*3:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__module_next_state;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__cpu_reset;
        CData/*1:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__cpu_op_out;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__stall_bp;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__stall_bp_csff;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__stall_bp_tck;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__stall_reg;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__stall_reg_csff;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__stall_reg_cpu;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__cpu_reset_csff;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__wr_reg;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__str_sync;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__rdy_sync;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__rdy_sync_tff1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__rdy_sync_tff2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__rdy_sync_tff2q;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__str_sync_wbff1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__str_sync_wbff2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__str_sync_wbff2q;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__data_o_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__rdy_sync_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__start_toggle;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__cpu_fsm_state;
        CData/*0:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__next_fsm_state;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__read_bit_count;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__write_bit_count;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__input_word_count;
    };
    struct {
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__output_word_count;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__user_word_count;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__data_out_shift_reg;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__rd_bit_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__rd_bit_ct_rst;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__wr_bit_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__wr_bit_ct_rst;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__in_word_ct_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__out_word_ct_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__in_word_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__out_word_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__user_word_ct_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__user_word_ct_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__out_reg_ld_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__out_reg_shift_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__out_reg_data_sel;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__biu_rd_strobe;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__biu_wr_strobe;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__data_to_in_word_counter;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__data_to_out_word_counter;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__data_to_user_word_counter;
        CData/*2:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__wr_module_state;
        CData/*2:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__wr_module_next_state;
        CData/*2:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__rd_module_state;
        CData/*2:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__rd_module_next_state;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__data_in;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rdata;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wen_tff;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__ren_tff;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wda_rst;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wpp;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__w_fifo_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__ren_rst;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rdata_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rpp;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__r_fifo_en;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__r_wb_ack;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__w_wb_ack;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wb_wr;
        CData/*1:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fsm_state;
        CData/*1:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__next_rd_fsm_state;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__reg_dlab_bit;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__reg_ier;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__thr_int_arm;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__reg_fcr_wren;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__fifo_access;
        CData/*1:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fsm_state;
        CData/*1:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__next_wr_fsm_state;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wen_sff__DOT__sync1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wen_sff__DOT__sync2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wen_sff__DOT__syncprev;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wen_sff__DOT__srflop;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wen_sff__DOT__syncxor;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__ren_sff__DOT__sync1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__ren_sff__DOT__sync2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__ren_sff__DOT__syncprev;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__ren_sff__DOT__srflop;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__ren_sff__DOT__syncxor;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__regA;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__regB;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__strobe_toggle;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__ack_toggle;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__A_enable;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__strobe_sff_out;
    };
    struct {
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__strobe_sff__DOT__sync1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__strobe_sff__DOT__sync2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__strobe_sff__DOT__syncprev;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__strobe_sff__DOT__srflop;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__strobe_sff__DOT__syncxor;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__ack_sff__DOT__sync1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__ack_sff__DOT__sync2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__ack_sff__DOT__syncprev;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__ack_sff__DOT__srflop;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__ack_sff__DOT__syncxor;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__regA;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__regB;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__strobe_toggle;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__ack_toggle;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__A_enable;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__strobe_sff_out;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__strobe_sff__DOT__sync1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__strobe_sff__DOT__sync2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__strobe_sff__DOT__syncprev;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__strobe_sff__DOT__srflop;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__strobe_sff__DOT__syncxor;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__ack_sff__DOT__sync1;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__ack_sff__DOT__sync2;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__ack_sff__DOT__syncprev;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__ack_sff__DOT__srflop;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__ack_sff__DOT__syncxor;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__reg0;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__reg1;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__reg2;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__reg3;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__reg4;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__reg5;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__reg6;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__reg7;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__counter;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__push_ok;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__pop_ok;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__reg0;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__reg1;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__reg2;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__reg3;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__reg4;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__reg5;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__reg6;
        CData/*7:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__reg7;
        CData/*3:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__counter;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__push_ok;
        CData/*0:0*/ __PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__pop_ok;
        CData/*0:0*/ __PVT__uart16550__DOT__we_o;
        CData/*0:0*/ __PVT__uart16550__DOT__re_o;
        CData/*7:0*/ __PVT__uart16550__DOT__wb_interface__DOT__wb_dat_is;
        CData/*2:0*/ __PVT__uart16550__DOT__wb_interface__DOT__wb_adr_is;
        CData/*0:0*/ __PVT__uart16550__DOT__wb_interface__DOT__wb_we_is;
        CData/*0:0*/ __PVT__uart16550__DOT__wb_interface__DOT__wb_cyc_is;
        CData/*0:0*/ __PVT__uart16550__DOT__wb_interface__DOT__wb_stb_is;
        CData/*0:0*/ __PVT__uart16550__DOT__wb_interface__DOT__wre;
        CData/*1:0*/ __PVT__uart16550__DOT__wb_interface__DOT__wbstate;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__enable;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__srx_pad;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__ier;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__iir;
        CData/*1:0*/ __PVT__uart16550__DOT__regs__DOT__fcr;
        CData/*4:0*/ __PVT__uart16550__DOT__regs__DOT__mcr;
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__lcr;
    };
    struct {
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__msr;
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__scratch;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__start_dlc;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr_mask_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__msi_reset;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__trigger_level;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rx_reset;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__tx_reset;
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__lsr;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr0;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr5;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr6;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr7;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr0r;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr1r;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr2r;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr3r;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr4r;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr5r;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr6r;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr7r;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr_mask;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rls_int;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rda_int;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__ti_int;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__thre_int;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__ms_int;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__tf_push;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rf_pop;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rf_overrun;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rf_push_pulse;
        CData/*4:0*/ __PVT__uart16550__DOT__regs__DOT__rf_count;
        CData/*4:0*/ __PVT__uart16550__DOT__regs__DOT__tf_count;
        CData/*2:0*/ __PVT__uart16550__DOT__regs__DOT__tstate;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__rstate;
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__block_cnt;
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__block_value;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__serial_in;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr_mask_condition;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__iir_read;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__msr_read;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__fifo_read;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__fifo_write;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__delayed_modem_signals;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr0_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr1_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr2_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr3_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr4_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr5_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr6_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__lsr7_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rls_int_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__thre_int_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__ms_int_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__ti_int_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rda_int_d;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rls_int_pnd;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__rda_int_pnd;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__thre_int_pnd;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__ms_int_pnd;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__ti_int_pnd;
        CData/*4:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__counter;
        CData/*2:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__bit_counter;
    };
    struct {
        CData/*6:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__shift_out;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__stx_o_tmp;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__parity_xor;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__tf_pop;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__bit_out;
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__tf_data_out;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__tf_overrun;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__top;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__bottom;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__top_plus_1;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__i_uart_sync_flops__DOT__flop_0;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rcounter16;
        CData/*2:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rbit_counter;
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rshift;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rparity;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rparity_error;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rframing_error;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rparity_xor;
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__counter_b;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rf_push_q;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rf_push;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rcounter16_eq_7;
        CData/*0:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rcounter16_eq_0;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rcounter16_minus_1;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__top;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__bottom;
        CData/*3:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__top_plus_1;
        SData/*10:0*/ __PVT__or1k_dbg_wp_o;
        SData/*15:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__word_count;
        SData/*15:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__data_to_word_counter;
        SData/*15:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__word_count;
        SData/*15:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__data_to_word_counter;
        SData/*15:0*/ __PVT__uart16550__DOT__regs__DOT__dl;
        SData/*15:0*/ __PVT__uart16550__DOT__regs__DOT__dlc;
        SData/*10:0*/ __PVT__uart16550__DOT__regs__DOT__rf_data_out;
        SData/*9:0*/ __PVT__uart16550__DOT__regs__DOT__counter_t;
        SData/*10:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__rf_data_in;
        SData/*9:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__toc_value;
        IData/*31:0*/ __PVT__wb_s2m_or1k_d_dat;
        IData/*31:0*/ __PVT__wb_s2m_or1k_i_dat;
        IData/*31:0*/ __PVT__wb_s2m_dbg_dat;
        IData/*31:0*/ __PVT__wb_m2s_uart_adr;
        IData/*31:0*/ __PVT__or1k_irq;
        IData/*31:0*/ __PVT__wb_interface0__DOT__wb_arbiter_mem__DOT__arbiter0__DOT__yy;
        IData/*31:0*/ __PVT__jtag_tap0__DOT__idcode_reg;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu1_addr_o;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu1_data_i;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu1_data_o;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb_jsp_adr_i;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb_jsp_dat_i;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__address_counter;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__data_to_addr_counter;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__data_to_biu;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__addr_reg;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__data_in_reg;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__data_out_reg;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_crc_i__DOT__crc;
        IData/*31:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_crc_i__DOT__new_crc;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__address_counter;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__data_out_shift_reg;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__data_to_addr_counter;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__addr_reg;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__data_in_reg;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__data_out_reg;
    };
    struct {
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_crc_i__DOT__crc;
        IData/*31:0*/ __PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_crc_i__DOT__new_crc;
        IData/*31:0*/ __PVT__uart16550__DOT__wb_dat32_o;
        QData/*52:0*/ __PVT__dbg_if0__DOT__input_shift_reg;
        QData/*32:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__data_out_shift_reg;
        QData/*32:0*/ __PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__internal_reg_error;
        CData/*2:0*/ __PVT__wb_interface0__DOT__wb_arbiter_mem__DOT__arbiter0__DOT__token_lookahead[3];
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__tfifo__DOT__ram[16];
        CData/*2:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__fifo[16];
        CData/*7:0*/ __PVT__uart16550__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__rfifo__DOT__ram[16];
    };
    
    // LOCAL VARIABLES
    CData/*0:0*/ dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT____Vcellinp__wr_fifo__RST;
    CData/*0:0*/ dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT____Vcellinp__rd_fifo__RST;
    CData/*1:0*/ wb_interface0__DOT____Vcellout__wb_mux_or1k_d__wbs_cyc_o;
    CData/*2:0*/ wb_interface0__DOT____Vcellout__wb_arbiter_mem__wbm_ack_o;
    CData/*2:0*/ wb_interface0__DOT____Vcellinp__wb_arbiter_mem__wbm_cyc_i;
    CData/*0:0*/ dbg_if0__DOT____Vcellout__wb__DOT__i_dbg_wb__top_inhibit_o;
    CData/*0:0*/ dbg_if0__DOT____Vcellout__cpu0__DOT__i_dbg_cpu_or1k__top_inhibit_o;
    CData/*0:0*/ __Vfunc_wb_interface0__DOT__wb_mux_or1k_d__DOT__ff1__0__Vfuncout;
    CData/*1:0*/ __Vfunc_wb_interface0__DOT__wb_mux_or1k_d__DOT__ff1__0__in;
    CData/*0:0*/ __Vfunc_wb_interface0__DOT__wb_mux_or1k_i__DOT__ff1__1__Vfuncout;
    CData/*0:0*/ __Vfunc_wb_interface0__DOT__wb_mux_or1k_i__DOT__ff1__1__in;
    CData/*0:0*/ __Vfunc_wb_interface0__DOT__wb_mux_dbg__DOT__ff1__2__Vfuncout;
    CData/*0:0*/ __Vfunc_wb_interface0__DOT__wb_mux_dbg__DOT__ff1__2__in;
    CData/*3:0*/ __Vtableidx1;
    CData/*3:0*/ __Vtableidx3;
    CData/*4:0*/ __Vtableidx4;
    CData/*3:0*/ __Vtableidx5;
    CData/*7:0*/ __Vtableidx6;
    CData/*6:0*/ __Vtableidx7;
    CData/*4:0*/ __Vtableidx8;
    CData/*1:0*/ __Vtableidx9;
    CData/*3:0*/ __Vtableidx10;
    CData/*7:0*/ __Vtableidx12;
    CData/*7:0*/ __Vtableidx13;
    CData/*0:0*/ __Vdly__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_statusreg_i__DOT__stall_reg;
    CData/*0:0*/ __Vdly__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__str_sync;
    CData/*0:0*/ __Vdly__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__biu_ready;
    CData/*0:0*/ __Vdly__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__rdy_sync;
    CData/*0:0*/ __Vdly__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__freespace_syncreg__DOT__strobe_toggle;
    CData/*0:0*/ __Vdly__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__bytesavail_syncreg__DOT__strobe_toggle;
    CData/*3:0*/ __Vdly__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__wr_fifo__DOT__counter;
    CData/*3:0*/ __Vdly__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rd_fifo__DOT__counter;
    SData/*8:0*/ __Vtableidx2;
    CData/*2:0*/ __Vtablechg11[32];
    static CData/*0:0*/ __Vtable1___PVT__jtag_tap0__DOT__extest_select[16];
    static CData/*0:0*/ __Vtable1___PVT__jtag_tap0__DOT__sample_preload_select[16];
    static CData/*0:0*/ __Vtable1___PVT__jtag_tap0__DOT__idcode_select[16];
    static CData/*0:0*/ __Vtable1___PVT__jtag_tap0__DOT__mbist_select[16];
    static CData/*0:0*/ __Vtable1___PVT__jtag_tap0__DOT__debug_select[16];
    static CData/*0:0*/ __Vtable1___PVT__jtag_tap0__DOT__bypass_select[16];
    static CData/*0:0*/ __Vtable2_tdo_pad_o[512];
    static CData/*5:0*/ __Vtable3___PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__word_size_bits[16];
    static CData/*2:0*/ __Vtable3___PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__word_size_bytes[16];
    static CData/*0:0*/ __Vtable3___PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__rd_op[16];
    static CData/*0:0*/ __Vtable4___PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__rdy_sync_en[32];
    static CData/*0:0*/ __Vtable4___PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__err_en[32];
    static CData/*0:0*/ __Vtable4___PVT__dbg_if0__DOT__wb__DOT__i_dbg_wb__DOT__wb_biu_i__DOT__data_o_en[32];
    static CData/*0:0*/ __Vtable4___PVT__wb_m2s_dbg_cyc[32];
    static CData/*0:0*/ __Vtable4___PVT__wb_m2s_dbg_stb[32];
    static CData/*0:0*/ __Vtable5___PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__rdy_sync_en[16];
    static CData/*0:0*/ __Vtable5___PVT__dbg_if0__DOT__cpu0__DOT__i_dbg_cpu_or1k__DOT__or1k_biu_i__DOT__data_o_en[16];
    static CData/*0:0*/ __Vtable5___PVT__or1k_dbg_stb_i[16];
    static CData/*2:0*/ __Vtable6___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__wr_module_next_state[256];
    static CData/*2:0*/ __Vtable7___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__rd_module_next_state[128];
    static CData/*1:0*/ __Vtable8___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__next_rd_fsm_state[32];
    static CData/*0:0*/ __Vtable9___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__ren_rst[4];
    static CData/*0:0*/ __Vtable9___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rpp[4];
    static CData/*0:0*/ __Vtable9___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__r_fifo_en[4];
    static CData/*0:0*/ __Vtable9___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__rdata_en[4];
    static CData/*0:0*/ __Vtable9___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__r_wb_ack[4];
    static CData/*1:0*/ __Vtable10___PVT__dbg_if0__DOT__genblk4__DOT__i_dbg_jsp__DOT__jsp_biu_i__DOT__next_wr_fsm_state[16];
    static CData/*0:0*/ __Vtable11___PVT__wb_s2m_uart_ack[32];
    static CData/*1:0*/ __Vtable11___PVT__uart16550__DOT__wb_interface__DOT__wbstate[32];
    static CData/*0:0*/ __Vtable11___PVT__uart16550__DOT__wb_interface__DOT__wre[32];
    static CData/*7:0*/ __Vtable12___PVT__uart16550__DOT__regs__DOT__block_value[256];
    static SData/*9:0*/ __Vtable13___PVT__uart16550__DOT__regs__DOT__receiver__DOT__toc_value[256];
    
    // INTERNAL VARIABLES
  private:
    Vor1k_pu__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vor1k_pu_or1k_pu);  ///< Copying not allowed
  public:
    Vor1k_pu_or1k_pu(const char* name = "TOP");
    ~Vor1k_pu_or1k_pu();
    
    // INTERNAL METHODS
    void __Vconfigure(Vor1k_pu__Syms* symsp, bool first);
    static void _combo__TOP__or1k_pu__15(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _combo__TOP__or1k_pu__21(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _combo__TOP__or1k_pu__28(Vor1k_pu__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _multiclk__TOP__or1k_pu__13(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__19(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__22(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__27(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__30(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__31(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__32(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__33(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__10(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__11(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__12(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__14(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__16(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__17(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__18(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__23(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__24(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__25(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__26(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__29(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__3(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__4(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__5(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__6(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__7(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__8(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__9(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _settle__TOP__or1k_pu__1(Vor1k_pu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__or1k_pu__2(Vor1k_pu__Syms* __restrict vlSymsp);
  private:
    static void traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
