// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vor1k_pu.h for the primary calling header

#ifndef _VOR1K_PU_OR1K_CPU_CAPPUCCINO__PI5_H_
#define _VOR1K_PU_OR1K_CPU_CAPPUCCINO__PI5_H_  // guard

#include "verilated_heavy.h"
#include "Vor1k_pu__Dpi.h"

//==========

class Vor1k_pu__Syms;
class Vor1k_pu_VerilatedVcd;


//----------

VL_MODULE(Vor1k_pu_or1k_cpu_cappuccino__pi5) {
  public:
    
    // PORTS
    VL_IN8(__PVT__clk,0,0);
    VL_IN8(__PVT__rst,0,0);
    VL_IN8(__PVT__ibus_err_i,0,0);
    VL_IN8(__PVT__ibus_ack_i,0,0);
    VL_OUT8(__PVT__ibus_req_o,0,0);
    VL_OUT8(__PVT__ibus_burst_o,0,0);
    VL_IN8(__PVT__dbus_err_i,0,0);
    VL_IN8(__PVT__dbus_ack_i,0,0);
    VL_OUT8(__PVT__dbus_req_o,0,0);
    VL_OUT8(__PVT__dbus_bsel_o,3,0);
    VL_OUT8(__PVT__dbus_we_o,0,0);
    VL_OUT8(__PVT__dbus_burst_o,0,0);
    VL_IN8(__PVT__du_stb_i,0,0);
    VL_IN8(__PVT__du_we_i,0,0);
    VL_OUT8(__PVT__du_ack_o,0,0);
    VL_IN8(__PVT__du_stall_i,0,0);
    VL_OUT8(__PVT__du_stall_o,0,0);
    VL_OUT8(__PVT__traceport_exec_valid_o,0,0);
    VL_OUT8(__PVT__traceport_exec_jb_o,0,0);
    VL_OUT8(__PVT__traceport_exec_jal_o,0,0);
    VL_OUT8(__PVT__traceport_exec_jr_o,0,0);
    VL_OUT8(__PVT__traceport_exec_wbreg_o,4,0);
    VL_OUT8(__PVT__traceport_exec_wben_o,0,0);
    VL_OUT8(__PVT__spr_bus_we_o,0,0);
    VL_OUT8(__PVT__spr_bus_stb_o,0,0);
    VL_IN8(__PVT__spr_bus_ack_mac_i,0,0);
    VL_IN8(__PVT__spr_bus_ack_pmu_i,0,0);
    VL_IN8(__PVT__spr_bus_ack_pcu_i,0,0);
    VL_IN8(__PVT__spr_bus_ack_fpu_i,0,0);
    VL_IN8(__PVT__snoop_en_i,0,0);
    VL_IN16(__PVT__du_addr_i,15,0);
    VL_OUT16(__PVT__spr_bus_addr_o,15,0);
    VL_OUT16(__PVT__spr_sr_o,15,0);
    VL_IN(__PVT__ibus_dat_i,31,0);
    VL_OUT(__PVT__ibus_adr_o,31,0);
    VL_IN(__PVT__dbus_dat_i,31,0);
    VL_OUT(__PVT__dbus_adr_o,31,0);
    VL_OUT(__PVT__dbus_dat_o,31,0);
    VL_IN(__PVT__irq_i,31,0);
    VL_IN(__PVT__du_dat_i,31,0);
    VL_OUT(__PVT__du_dat_o,31,0);
    VL_OUT(__PVT__traceport_exec_pc_o,31,0);
    VL_OUT(__PVT__traceport_exec_jbtarget_o,31,0);
    VL_OUT(__PVT__traceport_exec_insn_o,31,0);
    VL_OUT(__PVT__traceport_exec_wbdata_o,31,0);
    VL_OUT(__PVT__spr_bus_dat_o,31,0);
    VL_IN(__PVT__spr_bus_dat_mac_i,31,0);
    VL_IN(__PVT__spr_bus_dat_pmu_i,31,0);
    VL_IN(__PVT__spr_bus_dat_pcu_i,31,0);
    VL_IN(__PVT__spr_bus_dat_fpu_i,31,0);
    VL_IN(__PVT__multicore_coreid_i,31,0);
    VL_IN(__PVT__multicore_numcores_i,31,0);
    VL_IN(__PVT__snoop_adr_i,31,0);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __PVT__branch_mispredict_o;
        CData/*0:0*/ __PVT__ctrl_branch_exception_o;
        CData/*0:0*/ __PVT__ctrl_bubble_o;
        CData/*0:0*/ __PVT__ctrl_carry_clear_o;
        CData/*0:0*/ __PVT__ctrl_carry_set_o;
        CData/*0:0*/ __PVT__ctrl_except_align_o;
        CData/*0:0*/ __PVT__ctrl_except_dbus_o;
        CData/*0:0*/ __PVT__ctrl_except_dpagefault_o;
        CData/*0:0*/ __PVT__ctrl_except_dtlb_miss_o;
        CData/*0:0*/ __PVT__ctrl_except_ibus_align_o;
        CData/*0:0*/ __PVT__ctrl_except_ibus_err_o;
        CData/*0:0*/ __PVT__ctrl_except_illegal_o;
        CData/*0:0*/ __PVT__ctrl_except_ipagefault_o;
        CData/*0:0*/ __PVT__ctrl_except_itlb_miss_o;
        CData/*0:0*/ __PVT__ctrl_except_syscall_o;
        CData/*0:0*/ __PVT__ctrl_except_trap_o;
        CData/*0:0*/ __PVT__ctrl_flag_clear_o;
        CData/*0:0*/ __PVT__ctrl_flag_o;
        CData/*0:0*/ __PVT__ctrl_flag_set_o;
        CData/*1:0*/ __PVT__ctrl_lsu_length_o;
        CData/*0:0*/ __PVT__ctrl_lsu_zext_o;
        CData/*0:0*/ __PVT__ctrl_op_lsu_atomic_o;
        CData/*0:0*/ __PVT__ctrl_op_lsu_load_o;
        CData/*0:0*/ __PVT__ctrl_op_lsu_store_o;
        CData/*0:0*/ __PVT__ctrl_op_mfspr_o;
        CData/*0:0*/ __PVT__ctrl_op_msync_o;
        CData/*0:0*/ __PVT__ctrl_op_mtspr_o;
        CData/*0:0*/ __PVT__ctrl_op_mul_o;
        CData/*0:0*/ __PVT__ctrl_op_rfe_o;
        CData/*0:0*/ __PVT__ctrl_overflow_clear_o;
        CData/*0:0*/ __PVT__ctrl_overflow_set_o;
        CData/*0:0*/ __PVT__ctrl_fpcsr_set_o;
        CData/*0:0*/ __PVT__ctrl_rf_wb_o;
        CData/*4:0*/ __PVT__ctrl_rfd_adr_o;
        CData/*0:0*/ __PVT__decode_branch_o;
        CData/*0:0*/ __PVT__decode_bubble_o;
        CData/*0:0*/ __PVT__decode_except_ibus_err_o;
        CData/*0:0*/ __PVT__decode_except_illegal_o;
        CData/*0:0*/ __PVT__decode_except_ipagefault_o;
        CData/*0:0*/ __PVT__decode_except_itlb_miss_o;
        CData/*0:0*/ __PVT__decode_immediate_sel_o;
        CData/*1:0*/ __PVT__decode_lsu_length_o;
        CData/*0:0*/ __PVT__decode_op_brcond_o;
        CData/*0:0*/ __PVT__decode_op_div_signed_o;
        CData/*0:0*/ __PVT__decode_op_div_unsigned_o;
        CData/*0:0*/ __PVT__decode_op_jal_o;
        CData/*0:0*/ __PVT__decode_op_jr_o;
        CData/*0:0*/ __PVT__decode_op_lsu_store_o;
        CData/*0:0*/ __PVT__decode_op_mul_signed_o;
        CData/*0:0*/ __PVT__decode_op_mul_unsigned_o;
        CData/*0:0*/ __PVT__decode_op_setflag_o;
        CData/*0:0*/ __PVT__decode_valid_o;
        CData/*0:0*/ __PVT__execute_adder_do_carry_o;
        CData/*0:0*/ __PVT__execute_adder_do_sub_o;
        CData/*0:0*/ __PVT__execute_bubble_o;
        CData/*0:0*/ __PVT__execute_except_ibus_align_o;
        CData/*0:0*/ __PVT__execute_except_ibus_err_o;
        CData/*0:0*/ __PVT__execute_except_illegal_o;
        CData/*0:0*/ __PVT__execute_except_ipagefault_o;
        CData/*0:0*/ __PVT__execute_except_itlb_miss_o;
        CData/*0:0*/ __PVT__execute_except_syscall_o;
        CData/*0:0*/ __PVT__execute_except_trap_o;
        CData/*0:0*/ __PVT__execute_immediate_sel_o;
        CData/*1:0*/ __PVT__execute_lsu_length_o;
    };
    struct {
        CData/*0:0*/ __PVT__execute_lsu_zext_o;
        CData/*0:0*/ __PVT__execute_op_add_o;
        CData/*0:0*/ __PVT__execute_op_alu_o;
        CData/*0:0*/ __PVT__execute_op_bf_o;
        CData/*0:0*/ __PVT__execute_op_bnf_o;
        CData/*0:0*/ __PVT__execute_op_branch_o;
        CData/*0:0*/ __PVT__execute_op_brcond_o;
        CData/*0:0*/ __PVT__execute_op_div_o;
        CData/*0:0*/ __PVT__execute_op_div_signed_o;
        CData/*0:0*/ __PVT__execute_op_div_unsigned_o;
        CData/*0:0*/ __PVT__execute_op_ffl1_o;
        CData/*0:0*/ __PVT__execute_op_jal_o;
        CData/*0:0*/ __PVT__execute_op_jbr_o;
        CData/*0:0*/ __PVT__execute_op_jr_o;
        CData/*0:0*/ __PVT__execute_op_lsu_atomic_o;
        CData/*0:0*/ __PVT__execute_op_lsu_load_o;
        CData/*0:0*/ __PVT__execute_op_lsu_store_o;
        CData/*0:0*/ __PVT__execute_op_mfspr_o;
        CData/*0:0*/ __PVT__execute_op_movhi_o;
        CData/*0:0*/ __PVT__execute_op_ext_o;
        CData/*0:0*/ __PVT__execute_op_msync_o;
        CData/*0:0*/ __PVT__execute_op_mtspr_o;
        CData/*0:0*/ __PVT__execute_op_mul_o;
        CData/*0:0*/ __PVT__execute_op_mul_signed_o;
        CData/*0:0*/ __PVT__execute_op_mul_unsigned_o;
        CData/*0:0*/ __PVT__execute_op_rfe_o;
        CData/*0:0*/ __PVT__execute_op_setflag_o;
        CData/*0:0*/ __PVT__execute_op_shift_o;
        CData/*3:0*/ __PVT__execute_opc_alu_o;
        CData/*3:0*/ __PVT__execute_opc_alu_secondary_o;
        CData/*5:0*/ __PVT__execute_opc_insn_o;
        CData/*0:0*/ __PVT__execute_predicted_flag_o;
        CData/*0:0*/ __PVT__execute_rf_wb_o;
        CData/*4:0*/ __PVT__execute_rfd_adr_o;
        CData/*0:0*/ __PVT__fetch_exception_taken_o;
        CData/*0:0*/ __PVT__fetch_rf_adr_valid_o;
        CData/*0:0*/ __PVT__fetch_valid_o;
        CData/*0:0*/ __PVT__dcache_hit_o;
        CData/*0:0*/ __PVT__lsu_valid_o;
        CData/*0:0*/ __PVT__padv_decode_o;
        CData/*0:0*/ __PVT__padv_execute_o;
        CData/*0:0*/ __PVT__padv_fetch_o;
        CData/*0:0*/ __PVT__pipeline_flush_o;
        CData/*0:0*/ __PVT__predicted_flag_o;
        CData/*0:0*/ __PVT__spr_bus_ack_ic_i;
        CData/*0:0*/ __PVT__store_buffer_err_o;
        CData/*0:0*/ __PVT__wb_rf_wb_o;
        CData/*4:0*/ __PVT__wb_rfd_adr_o;
        CData/*0:0*/ __PVT__traceport_jal_execute_to_ctrl;
        CData/*0:0*/ __PVT__traceport_jr_execute_to_ctrl;
        CData/*0:0*/ __PVT__traceport_waitexec;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__ctrl_branch_exception_r;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__bus_access_done;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__ctrl_branch_exception_edge;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__stall_fetch_valid;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__addr_valid;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__flush;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__nop_ack;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__imem_err;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__ic_invalidate;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__ic_access;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_cache_inhibit;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__pagefault;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__tlb_miss;
    };
    struct {
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__except_itlb_miss;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__except_ipagefault;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_busy;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__tlb_reload_ack;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__fetching_brcond;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__fetching_mispredicted_branch;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__mispredict_stall;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__exception_while_tlb_reload;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__except_ipagefault_clear;
        CData/*2:0*/ __PVT__or1k_fetch_cappuccino__DOT__state;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__ibus_req;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__ibus_ack;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__ibus_access;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__ic_enable_r;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__ic_req;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__immu_spr_bus_stb;
        CData/*3:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__state;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__refill;
        CData/*7:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__invalidate_adr;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__refill_done;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__refill_hit;
        CData/*7:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__refill_valid;
        CData/*7:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__refill_valid_r;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_lru_in;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_we;
        CData/*1:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_we;
        CData/*1:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_hit;
        CData/*1:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__lru;
        CData/*1:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_save_lru;
        CData/*1:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__access;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__next_lru_history;
        CData/*1:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__gen_u_lru__DOT__u_lru__DOT__lru_post;
        CData/*5:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_addr;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_we;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_huge_we;
        CData/*5:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_addr;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_we;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_huge_we;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_reload_we;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_reload_we;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_spr_cs;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_spr_cs_r;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_spr_cs;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_spr_cs_r;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__immucr_spr_cs_r;
        CData/*1:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__spr_way_idx_full;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__spr_way_idx_r;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__way_hit;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__way_huge_hit;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__tlb_reload_pagefault;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__tlb_reload_huge;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__sxe;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__uxe;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__spr_bus_ack;
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__spr_bus_ack_r;
        CData/*0:0*/ __PVT__or1k_decode__DOT__imm_sext_sel;
        CData/*0:0*/ __PVT__or1k_decode__DOT__imm_zext_sel;
        CData/*0:0*/ __PVT__or1k_decode__DOT__decode_except_ibus_align;
        CData/*0:0*/ __PVT__or1k_decode_execute_cappuccino__DOT__ctrl_to_decode_interlock;
        CData/*0:0*/ __PVT__or1k_decode_execute_cappuccino__DOT__branch_to_imm;
        CData/*0:0*/ __PVT__or1k_execute_alu__DOT__adder_carryout;
        CData/*0:0*/ __PVT__or1k_execute_alu__DOT__adder_signed_overflow;
        CData/*0:0*/ __PVT__or1k_execute_alu__DOT__carry_in;
        CData/*0:0*/ __PVT__or1k_execute_alu__DOT__flag_set;
    };
    struct {
        CData/*0:0*/ __PVT__or1k_execute_alu__DOT__mul_signed_overflow;
        CData/*3:0*/ __PVT__or1k_execute_alu__DOT__logic_lut;
        CData/*2:0*/ __PVT__or1k_execute_alu__DOT__threestagemultiply__DOT__mul_valid_shr;
        CData/*5:0*/ __PVT__or1k_execute_alu__DOT__genblk3__DOT__div_count;
        CData/*0:0*/ __PVT__or1k_execute_alu__DOT__genblk3__DOT__div_neg;
        CData/*0:0*/ __PVT__or1k_execute_alu__DOT__genblk3__DOT__div_done;
        CData/*0:0*/ __PVT__or1k_execute_alu__DOT__genblk3__DOT__div_by_zero_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__access_done;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__except_align;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__except_dbus;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_ack;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_err;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_we;
        CData/*3:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_bsel;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_access;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_stall;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__lsu_ack;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_err;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_we;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_access;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_refill_allowed;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_enable_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_enabled;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__ctrl_op_lsu;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__tlb_miss;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__pagefault;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__except_dtlb_miss;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__except_dtlb_miss_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__except_dpagefault;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__except_dpagefault_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_cache_inhibit;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__tlb_reload_req;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__tlb_reload_ack;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__tlb_reload_done;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_write;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_read;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_full;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_empty;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_write_pending;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_atomic;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__last_write;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__write_done;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__atomic_reserve;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__swa_success;
        CData/*2:0*/ __PVT__or1k_lsu_cappuccino__DOT__state;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_refill_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__atomic_gen__DOT__atomic_flag_set;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__atomic_gen__DOT__atomic_flag_clear;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__dc_req;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__dmmu_spr_bus_stb;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_gen__DOT__or1k_store_buffer__DOT__fifo_ram__DOT__bypass_gen__DOT__bypass;
        CData/*4:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__state;
        CData/*7:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__invalidate_adr;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__refill_done;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__refill_hit;
        CData/*7:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__refill_valid;
        CData/*7:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__refill_valid_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__invalidate;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_lru_in;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_we;
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_we;
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_hit;
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__lru;
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_save_lru;
    };
    struct {
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__access;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__next_lru_history;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__write_pending;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_check;
        CData/*7:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_windex;
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_way_hit;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__invalidate_ack;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_memories__BRA__0__KET____DOT__way_data_ram__DOT__bypass_gen__DOT__bypass;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_memories__BRA__1__KET____DOT__way_data_ram__DOT__bypass_gen__DOT__bypass;
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__gen_u_lru__DOT__u_lru__DOT__lru_post;
        CData/*5:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_addr;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_we;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_huge_we;
        CData/*5:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_addr;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_we;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_huge_we;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_reload_we;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_reload_we;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_spr_cs;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_spr_cs_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_spr_cs;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_spr_cs_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dmmucr_spr_cs_r;
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__spr_way_idx_full;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__spr_way_idx_r;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__way_hit;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__way_huge_hit;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__tlb_reload_pagefault;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__tlb_reload_huge;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__ure;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__uwe;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__sre;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__swe;
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__spr_bus_ack;
        CData/*0:0*/ __PVT__or1k_wb_mux_cappuccino__DOT__wb_op_mul;
        CData/*5:0*/ __PVT__or1k_rf_cappuccino__DOT__rfa_rdad;
        CData/*5:0*/ __PVT__or1k_rf_cappuccino__DOT__rfb_rdad;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__rf_wren;
        CData/*5:0*/ __PVT__or1k_rf_cappuccino__DOT__rf_wradr;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__flushing;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__execute_hazard_a;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__execute_hazard_b;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__ctrl_hazard_a;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__ctrl_hazard_b;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__wb_hazard_a;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__wb_hazard_b;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__use_last_wb_a;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__wb_to_decode_bypass_a;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__use_last_wb_b;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__wb_to_decode_bypass_b;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__genblk1__DOT__spr_gpr_we;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__genblk1__DOT__spr_gpr_re;
        CData/*0:0*/ __PVT__or1k_rf_cappuccino__DOT__genblk1__DOT__spr_gpr_read_ack;
        CData/*5:0*/ __PVT__or1k_rf_cappuccino__DOT__genblk1__DOT__wb_rfd_adr_expand;
        CData/*0:0*/ __PVT__or1k_execute_ctrl_cappuccino__DOT__ctrl_stall;
        CData/*0:0*/ __PVT__or1k_execute_ctrl_cappuccino__DOT__execute_stall;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__execute_delay_slot;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__ctrl_delay_slot;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__execute_waiting_r;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__decode_execute_halt;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__exception_taken;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__padv_ctrl;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__exception_r;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__waiting_for_fetch;
    };
    struct {
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__doing_rfe_r;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__doing_rfe;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__deassert_doing_rfe;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__exception;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__ctrl_stage_exceptions;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__exception_re;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__except_ticktimer;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__except_pic;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__except_range;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__deassert_decode_execute_halt;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__cpu_stall;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__du_restart_from_stall;
        CData/*5:0*/ __PVT__or1k_ctrl_cappuccino__DOT__pstep;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__stepping;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__stepped_into_exception;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__stepped_into_rfe;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__du_npc_write;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__du_npc_written;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_we;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_ack;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_write_access;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_bus_access;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__ctrl_flag_clear;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__ctrl_flag_set;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__du__DOT__du_ack;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__du__DOT__du_stall_r;
        CData/*1:0*/ __PVT__or1k_ctrl_cappuccino__DOT__du__DOT__branch_step;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__pic__DOT__or1k_pic__DOT__spr_picmr_access;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__tt__DOT__or1k_ticktimer__DOT__spr_ttmr_access;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__tt__DOT__or1k_ticktimer__DOT__spr_ttcr_access;
        CData/*0:0*/ __PVT__or1k_ctrl_cappuccino__DOT__tt__DOT__or1k_ticktimer__DOT__ttcr_match;
        SData/*11:0*/ __PVT__ctrl_fpcsr_o;
        SData/*15:0*/ __PVT__decode_imm16_o;
        SData/*15:0*/ __PVT__execute_imm16_o;
        SData/*9:0*/ __PVT__execute_immjbr_upper_o;
        SData/*8:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_gen__DOT__or1k_store_buffer__DOT__write_pointer;
        SData/*8:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_gen__DOT__or1k_store_buffer__DOT__read_pointer;
        SData/*15:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_sr;
        SData/*15:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_esr;
        SData/*11:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_fpcsr;
        SData/*15:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_addr;
        SData/*11:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_access;
        SData/*11:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_access_ack;
        IData/*31:0*/ __PVT__pc_fetch_to_decode;
        IData/*31:0*/ __PVT__insn_fetch_to_decode;
        IData/*31:0*/ __PVT__pc_decode_to_execute;
        IData/*31:0*/ __PVT__pc_execute_to_ctrl;
        IData/*31:0*/ __PVT__alu_result_o;
        IData/*31:0*/ __PVT__ctrl_alu_result_o;
        IData/*31:0*/ __PVT__ctrl_epcr_o;
        IData/*31:0*/ __PVT__ctrl_lsu_adr_o;
        IData/*31:0*/ __PVT__ctrl_rfb_o;
        IData/*31:0*/ __PVT__decode_branch_target_o;
        IData/*31:0*/ __PVT__decode_immediate_o;
        IData/*31:0*/ __PVT__decode_rfb_o;
        IData/*31:0*/ __PVT__execute_immediate_o;
        IData/*31:0*/ __PVT__execute_jal_result_o;
        IData/*31:0*/ __PVT__execute_mispredict_target_o;
        IData/*31:0*/ __PVT__execute_rfa_o;
        IData/*31:0*/ __PVT__execute_rfb_o;
        IData/*31:0*/ __PVT__mfspr_dat_o;
        IData/*31:0*/ __PVT__rf_result_o;
        IData/*31:0*/ __PVT__spr_bus_dat_dc_i;
        IData/*31:0*/ __PVT__spr_bus_dat_ic_i;
    };
    struct {
        IData/*31:0*/ __PVT__traceport_stage_decode_insn;
        IData/*31:0*/ __PVT__traceport_stage_exec_insn;
        IData/*31:0*/ __PVT__traceport_jbtarget_decode_to_execute;
        IData/*31:0*/ __PVT__traceport_jbtarget_execute_to_ctrl;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__pc_fetch;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__pc_addr;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__imem_dat;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__ic_dat;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__ic_addr;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__ic_addr_match;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_phys_addr;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__tlb_reload_data;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__ibus_adr;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__next_ibus_adr;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__ibus_dat;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__w1;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__w2;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_memories__BRA__0__KET____DOT__way_data_ram__DOT__rdata;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_memories__BRA__1__KET____DOT__way_data_ram__DOT__rdata;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__gen_u_lru__DOT__u_lru__DOT__j;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__gen_u_lru__DOT__u_lru__DOT__offset;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_din;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_din;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_reload_din;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_reload_din;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__immucr;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__spr_bus_dat;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__spr_bus_dat_r;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb__BRA__0__KET____DOT__itlb_match_regs__DOT__rdata_a;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb__BRA__0__KET____DOT__itlb_match_regs__DOT__rdata_b;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb__BRA__0__KET____DOT__itlb_translate_regs__DOT__rdata_a;
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb__BRA__0__KET____DOT__itlb_translate_regs__DOT__rdata_b;
        IData/*31:0*/ __PVT__or1k_decode_execute_cappuccino__DOT__branch_to_imm_target;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__b;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__adder_result;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__b_mux;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__shift_result;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__logic_result;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__ext_result;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__threestagemultiply__DOT__mul_opa;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__threestagemultiply__DOT__mul_opb;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__threestagemultiply__DOT__mul_result1;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__threestagemultiply__DOT__mul_result2;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__genblk3__DOT__div_n;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__genblk3__DOT__div_d;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__genblk3__DOT__div_r;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__genblk5__DOT__ffl1_result_wire;
        IData/*31:0*/ __PVT__or1k_execute_alu__DOT__barrel_shifter__DOT__shift_lsw;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_dat_aligned;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_dat;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dbus_adr;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__next_dbus_adr;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__lsu_ldat;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__lsu_sdat;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_ldat;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_sdat;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_adr;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dc_adr_match;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_phys_addr;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__tlb_reload_addr;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__tlb_reload_data;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__atomic_addr;
        WData/*100:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_gen__DOT__or1k_store_buffer__DOT__fifo_dout[4];
        WData/*100:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_gen__DOT__or1k_store_buffer__DOT__fifo_din[4];
    };
    struct {
        WData/*100:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_gen__DOT__or1k_store_buffer__DOT__fifo_ram__DOT__rdata[4];
        WData/*100:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_gen__DOT__or1k_store_buffer__DOT__fifo_ram__DOT__bypass_gen__DOT__din_r[4];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_wr_dat;
        IData/*17:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_tag;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__w1;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__w2;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_memories__BRA__0__KET____DOT__way_data_ram__DOT__rdata;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_memories__BRA__0__KET____DOT__way_data_ram__DOT__bypass_gen__DOT__din_r;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_memories__BRA__1__KET____DOT__way_data_ram__DOT__rdata;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_memories__BRA__1__KET____DOT__way_data_ram__DOT__bypass_gen__DOT__din_r;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__gen_u_lru__DOT__u_lru__DOT__j;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__gen_u_lru__DOT__u_lru__DOT__offset;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_din;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_din;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_reload_din;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_reload_din;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dmmucr;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb__BRA__0__KET____DOT__dtlb_match_regs__DOT__rdata_a;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb__BRA__0__KET____DOT__dtlb_match_regs__DOT__rdata_b;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb__BRA__0__KET____DOT__dtlb_translate_regs__DOT__rdata_a;
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb__BRA__0__KET____DOT__dtlb_translate_regs__DOT__rdata_b;
        IData/*31:0*/ __PVT__or1k_wb_mux_cappuccino__DOT__rf_result;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__wb_hazard_result;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__execute_rfa;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__execute_rfb;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__rf_wrdat;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__execute_hazard_result_r;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__execute_hazard_result;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__ctrl_hazard_result_r;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__ctrl_hazard_result;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__wb_to_decode_result_a;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__wb_to_decode_result_b;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__rfa__DOT__rdata;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__rfb__DOT__rdata;
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__rfspr_gen__DOT__rfspr__DOT__rdata;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_epcr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_eear;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_evbar;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_ppc;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_npc;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__last_branch_insn_pc;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__last_branch_target_pc;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__exception_pc_addr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_dmr1;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_dmr2;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_dsr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_drr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_write_dat;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_sys_group_read;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_vr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_vr2;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_avr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_upr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_cpucfgr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_dmmucfgr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_immucfgr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_dccfgr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_iccfgr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__du__DOT__du_read_dat;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__pic__DOT__or1k_pic__DOT__spr_picmr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__pic__DOT__or1k_pic__DOT__spr_picsr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__pic__DOT__or1k_pic__DOT__irq_unmasked;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__tt__DOT__or1k_ticktimer__DOT__spr_ttmr;
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__tt__DOT__or1k_ticktimer__DOT__spr_ttcr;
    };
    struct {
        QData/*40:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_din;
        QData/*40:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_ram__DOT__rdata;
        QData/*32:0*/ __PVT__or1k_execute_alu__DOT__genblk3__DOT__div_sub;
        QData/*38:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_din;
        QData/*38:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_dout;
        QData/*38:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_ram__DOT__rdata;
        IData/*19:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_way_out[2];
        IData/*19:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_way_in[2];
        IData/*19:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_way_save[2];
        SData/*10:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_raddr[2];
        SData/*10:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_waddr[2];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_din[2];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_dout[2];
        IData/*18:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__check_way_tag[2];
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__check_way_match[2];
        CData/*0:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__check_way_valid[2];
        QData/*40:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__tag_ram__DOT__mem[256];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_memories__BRA__0__KET____DOT__way_data_ram__DOT__mem[2048];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__way_memories__BRA__1__KET____DOT__way_data_ram__DOT__mem[2048];
        CData/*1:0*/ __PVT__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__gen_u_lru__DOT__u_lru__DOT__expand[2];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_dout[1];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_match_huge_dout[1];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_dout[1];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb_trans_huge_dout[1];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb__BRA__0__KET____DOT__itlb_match_regs__DOT__mem[64];
        IData/*31:0*/ __PVT__or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT__itlb__BRA__0__KET____DOT__itlb_translate_regs__DOT__mem[64];
        WData/*100:0*/ __PVT__or1k_lsu_cappuccino__DOT__store_buffer_gen__DOT__or1k_store_buffer__DOT__fifo_ram__DOT__mem[256][4];
        IData/*18:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_way_out[2];
        IData/*18:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_way_in[2];
        IData/*18:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_way_save[2];
        SData/*10:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_raddr[2];
        SData/*10:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_waddr[2];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_din[2];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_dout[2];
        IData/*17:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__check_way_tag[2];
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__check_way_match[2];
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__check_way_valid[2];
        IData/*18:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_way_out[2];
        IData/*17:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_check_way_tag[2];
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_check_way_match[2];
        CData/*0:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__snoop_check_way_valid[2];
        QData/*38:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__tag_ram__DOT__mem[256];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_memories__BRA__0__KET____DOT__way_data_ram__DOT__mem[2048];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__way_memories__BRA__1__KET____DOT__way_data_ram__DOT__mem[2048];
        CData/*1:0*/ __PVT__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__gen_u_lru__DOT__u_lru__DOT__expand[2];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_dout[1];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_match_huge_dout[1];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_dout[1];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb_trans_huge_dout[1];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb__BRA__0__KET____DOT__dtlb_match_regs__DOT__mem[64];
        IData/*31:0*/ __PVT__or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT__dtlb__BRA__0__KET____DOT__dtlb_translate_regs__DOT__mem[64];
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__rfa__DOT__mem[64];
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__rfb__DOT__mem[64];
        IData/*31:0*/ __PVT__or1k_rf_cappuccino__DOT__rfspr_gen__DOT__rfspr__DOT__mem[64];
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_internal_read_dat[12];
        IData/*31:0*/ __PVT__or1k_ctrl_cappuccino__DOT__spr_isr[8];
    };
    
    // LOCAL VARIABLES
    CData/*0:0*/ or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__gen_u_lru__DOT__u_lru__DOT____Vlvbound1;
    CData/*0:0*/ or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT____Vlvbound3;
    CData/*0:0*/ or1k_fetch_cappuccino__DOT__immu_gen__DOT__or1k_immu__DOT____Vlvbound6;
    CData/*0:0*/ or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__gen_u_lru__DOT__u_lru__DOT____Vlvbound1;
    CData/*0:0*/ or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT____Vlvbound3;
    CData/*0:0*/ or1k_lsu_cappuccino__DOT__dmmu_gen__DOT__or1k_dmmu__DOT____Vlvbound6;
    CData/*5:0*/ __Vtableidx1;
    CData/*6:0*/ __Vtableidx2;
    CData/*6:0*/ __Vtableidx3;
    CData/*0:0*/ __Vdly__or1k_fetch_cappuccino__DOT__nop_ack;
    CData/*0:0*/ __Vdly__or1k_fetch_cappuccino__DOT__ibus_ack;
    CData/*0:0*/ __Vdly__or1k_fetch_cappuccino__DOT__tlb_reload_ack;
    CData/*2:0*/ __Vdly__or1k_fetch_cappuccino__DOT__state;
    CData/*3:0*/ __Vdly__or1k_fetch_cappuccino__DOT__icache_gen__DOT__or1k_icache__DOT__state;
    CData/*0:0*/ __Vdly__or1k_lsu_cappuccino__DOT__dbus_ack;
    CData/*0:0*/ __Vdly__or1k_lsu_cappuccino__DOT__tlb_reload_ack;
    CData/*2:0*/ __Vdly__or1k_lsu_cappuccino__DOT__state;
    CData/*0:0*/ __Vdly__dbus_req_o;
    CData/*0:0*/ __Vdly__or1k_lsu_cappuccino__DOT__last_write;
    CData/*4:0*/ __Vdly__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__state;
    CData/*0:0*/ __Vdly__or1k_lsu_cappuccino__DOT__dcache_gen__DOT__or1k_dcache__DOT__write_pending;
    SData/*15:0*/ __Vdly__or1k_ctrl_cappuccino__DOT__spr_sr;
    IData/*31:0*/ __Vfunc_or1k_execute_alu__DOT__barrel_shifter__DOT__reverse__0__Vfuncout;
    IData/*31:0*/ __Vfunc_or1k_execute_alu__DOT__barrel_shifter__DOT__reverse__0__in;
    IData/*31:0*/ __Vfunc_or1k_execute_alu__DOT__barrel_shifter__DOT__reverse__1__Vfuncout;
    IData/*31:0*/ __Vfunc_or1k_execute_alu__DOT__barrel_shifter__DOT__reverse__1__in;
    static CData/*1:0*/ __Vtable1___PVT__decode_lsu_length_o[64];
    static CData/*0:0*/ __Vtable2___PVT__or1k_execute_alu__DOT__flag_set[128];
    static CData/*3:0*/ __Vtable3___PVT__or1k_execute_alu__DOT__logic_lut[128];
    
    // INTERNAL VARIABLES
  private:
    Vor1k_pu__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vor1k_pu_or1k_cpu_cappuccino__pi5);  ///< Copying not allowed
  public:
    Vor1k_pu_or1k_cpu_cappuccino__pi5(const char* name = "TOP");
    ~Vor1k_pu_or1k_cpu_cappuccino__pi5();
    
    // INTERNAL METHODS
    void __Vconfigure(Vor1k_pu__Syms* symsp, bool first);
    static void _combo__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__14(Vor1k_pu__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _multiclk__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__10(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__13(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__9(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__11(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__12(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__3(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__4(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__5(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__6(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__7(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _sequent__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__8(Vor1k_pu__Syms* __restrict vlSymsp);
    static void _settle__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__1(Vor1k_pu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__or1k_pu__core__or1k_cpu__cappuccino__DOT__or1k_cpu__2(Vor1k_pu__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    uint32_t get_gpr(uint32_t gpr_num);
  private:
    static void traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
